### ISSUE TITLE
Potential Nuget Issues

### ISSUE THREAD

**Issue by dakamojo** [ctacke/opennetcf-ioc#4]
I noticed two things that I think are issues with the nuget distributions.

1) I'm using the package manager in Xamarin Studio.  When a new version of the nuget is published, the package manager does not recognize that there is a new version.  Instead the new version is listed as a completely new package.  I'm not sure if this is intentional.

2) The iOS package seems to work ok.  Now I'm working on the Android side.  When I add the nuget to my iOS project it adds two references (OpenNETCF.Google.Analytics and OpenNETCF.Google.Analytics.iOS).  For Android it only adds one reference (OpenNETCF.Google.Analytics).  It does not add a reference to the assembly that has the Android specific classes.  I can't figure out how to add the reference manually.  I think I need that reference so that I can call GA.Init() to get the device specific UserAgent.

**Comment by ctacke** [comment]
I've done a lot of rework to make this a .NET Standard library, which resolves these issues.
